// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.2
// source: proto/signing.proto

package signingpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"` // org whose key to sign with
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // specific key version (empty = use current)
	Digest        []byte                 `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest,omitempty"`            // raw bytes to sign (typically SHA-256 hash)
	Caller        string                 `protobuf:"bytes,4,opt,name=caller,proto3" json:"caller,omitempty"`            // calling service name for audit log
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_signing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SignRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *SignRequest) GetCaller() string {
	if x != nil {
		return x.Caller
	}
	return ""
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`          // key ID used
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`               // Ed25519 signature (64 bytes)
	SignedAt      string                 `protobuf:"bytes,3,opt,name=signed_at,json=signedAt,proto3" json:"signed_at,omitempty"` // RFC3339 timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_signing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetSignedAt() string {
	if x != nil {
		return x.SignedAt
	}
	return ""
}

type GetPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // empty = current key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyRequest) Reset() {
	*x = GetPublicKeyRequest{}
	mi := &file_proto_signing_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyRequest) ProtoMessage() {}

func (x *GetPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*GetPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{2}
}

func (x *GetPublicKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetPublicKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

type GetPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Ed25519 public key (32 bytes)
	Algorithm     string                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`                  // "Ed25519"
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublicKeyResponse) Reset() {
	*x = GetPublicKeyResponse{}
	mi := &file_proto_signing_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublicKeyResponse) ProtoMessage() {}

func (x *GetPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*GetPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublicKeyResponse) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *GetPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetPublicKeyResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *GetPublicKeyResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type RotateKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyRequest) Reset() {
	*x = RotateKeyRequest{}
	mi := &file_proto_signing_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyRequest) ProtoMessage() {}

func (x *RotateKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{4}
}

func (x *RotateKeyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RotateKeyRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RotateKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewKeyId      string                 `protobuf:"bytes,1,opt,name=new_key_id,json=newKeyId,proto3" json:"new_key_id,omitempty"`
	OldKeyId      string                 `protobuf:"bytes,2,opt,name=old_key_id,json=oldKeyId,proto3" json:"old_key_id,omitempty"`
	RotatedAt     string                 `protobuf:"bytes,3,opt,name=rotated_at,json=rotatedAt,proto3" json:"rotated_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateKeyResponse) Reset() {
	*x = RotateKeyResponse{}
	mi := &file_proto_signing_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateKeyResponse) ProtoMessage() {}

func (x *RotateKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_signing_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_signing_proto_rawDescGZIP(), []int{5}
}

func (x *RotateKeyResponse) GetNewKeyId() string {
	if x != nil {
		return x.NewKeyId
	}
	return ""
}

func (x *RotateKeyResponse) GetOldKeyId() string {
	if x != nil {
		return x.OldKeyId
	}
	return ""
}

func (x *RotateKeyResponse) GetRotatedAt() string {
	if x != nil {
		return x.RotatedAt
	}
	return ""
}

var File_proto_signing_proto protoreflect.FileDescriptor

const file_proto_signing_proto_rawDesc = "" +
	"\n" +
	"\x13proto/signing.proto\x12\n" +
	"signing.v1\"k\n" +
	"\vSignRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12\x16\n" +
	"\x06digest\x18\x03 \x01(\fR\x06digest\x12\x16\n" +
	"\x06caller\x18\x04 \x01(\tR\x06caller\"`\n" +
	"\fSignResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\x12\x1b\n" +
	"\tsigned_at\x18\x03 \x01(\tR\bsignedAt\"C\n" +
	"\x13GetPublicKeyRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\"\x89\x01\n" +
	"\x14GetPublicKeyResponse\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"A\n" +
	"\x10RotateKeyRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"n\n" +
	"\x11RotateKeyResponse\x12\x1c\n" +
	"\n" +
	"new_key_id\x18\x01 \x01(\tR\bnewKeyId\x12\x1c\n" +
	"\n" +
	"old_key_id\x18\x02 \x01(\tR\boldKeyId\x12\x1d\n" +
	"\n" +
	"rotated_at\x18\x03 \x01(\tR\trotatedAt2\xe8\x01\n" +
	"\x0eSigningService\x129\n" +
	"\x04Sign\x12\x17.signing.v1.SignRequest\x1a\x18.signing.v1.SignResponse\x12Q\n" +
	"\fGetPublicKey\x12\x1f.signing.v1.GetPublicKeyRequest\x1a .signing.v1.GetPublicKeyResponse\x12H\n" +
	"\tRotateKey\x12\x1c.signing.v1.RotateKeyRequest\x1a\x1d.signing.v1.RotateKeyResponseB6Z4github.com/attest-ai/signing_service/proto/signingpbb\x06proto3"

var (
	file_proto_signing_proto_rawDescOnce sync.Once
	file_proto_signing_proto_rawDescData []byte
)

func file_proto_signing_proto_rawDescGZIP() []byte {
	file_proto_signing_proto_rawDescOnce.Do(func() {
		file_proto_signing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_signing_proto_rawDesc), len(file_proto_signing_proto_rawDesc)))
	})
	return file_proto_signing_proto_rawDescData
}

var file_proto_signing_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_signing_proto_goTypes = []any{
	(*SignRequest)(nil),          // 0: signing.v1.SignRequest
	(*SignResponse)(nil),         // 1: signing.v1.SignResponse
	(*GetPublicKeyRequest)(nil),  // 2: signing.v1.GetPublicKeyRequest
	(*GetPublicKeyResponse)(nil), // 3: signing.v1.GetPublicKeyResponse
	(*RotateKeyRequest)(nil),     // 4: signing.v1.RotateKeyRequest
	(*RotateKeyResponse)(nil),    // 5: signing.v1.RotateKeyResponse
}
var file_proto_signing_proto_depIdxs = []int32{
	0, // 0: signing.v1.SigningService.Sign:input_type -> signing.v1.SignRequest
	2, // 1: signing.v1.SigningService.GetPublicKey:input_type -> signing.v1.GetPublicKeyRequest
	4, // 2: signing.v1.SigningService.RotateKey:input_type -> signing.v1.RotateKeyRequest
	1, // 3: signing.v1.SigningService.Sign:output_type -> signing.v1.SignResponse
	3, // 4: signing.v1.SigningService.GetPublicKey:output_type -> signing.v1.GetPublicKeyResponse
	5, // 5: signing.v1.SigningService.RotateKey:output_type -> signing.v1.RotateKeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_signing_proto_init() }
func file_proto_signing_proto_init() {
	if File_proto_signing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_signing_proto_rawDesc), len(file_proto_signing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_signing_proto_goTypes,
		DependencyIndexes: file_proto_signing_proto_depIdxs,
		MessageInfos:      file_proto_signing_proto_msgTypes,
	}.Build()
	File_proto_signing_proto = out.File
	file_proto_signing_proto_goTypes = nil
	file_proto_signing_proto_depIdxs = nil
}
